### ISSUE TITLE
Code Duplication

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#20]
Code in Member#member_ids and Owner#owner_ids seems to be very similar.
Refactoring needed?

**Comment by dbraga** [comment]
The code is practically the same until the Nokogiri call.
We could save like 3 lines of code, but where to put the method in common ? under entity?

**Comment by davide-targa** [comment]
The nokogiri call is the same too...
The only differrence is the assignment of the "entry_details" variable that I added only in Member class.
Do you confirm this?

**Comment by dbraga** [comment]
Not only.
If you look closer you have

From owner_ids: 
        if entry.css("apps|property[name]")[1].attributes["value"].value.eql?(entity)
          # Fill the array with the username
          entity_ids << entry.css("apps|property[name]")[0].attributes["value"].value.split("@")[0]
        end

From member_ids:
        entry_details = entry.css("apps|property[name]")
        if entry_details[0].attributes["value"].value.eql?(entity)
          # Fill the array with the username
          entity_ids << entry_details[1].attributes["value"].value.split("@")[0]
        end

**Comment by dbraga** [comment]
not sure why you referenced that commit ?

**Comment by davide-targa** [comment]
mmmh... maybe I was drunk
Anyway can you confirm that the modifications in 66a1242c72cbe378fde3902664bec929e8d17e46 work?

**Comment by dbraga** [comment]
They seem to work, i tried few times with Group.

**Comment by davide-targa** [comment]
If you agree I would close this issue for now... I mean the 'original' issue
