### ISSUE TITLE
Unused variable?

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#21]
Class Group (group.rb)
line 332: user = User.find(entity_id)
1 - La variabile user sembra inutilizzata all'interno del metodo;
2 - Se il pto 1 è vero, la find ha qualche utilità o mi sfugge qualcosa?

**Comment by dbraga** [comment]
E' inutilizzata.
Il motivo che e' li era per forzare il filtraggio sull'aggiunta di membri/owner.
O meglio "metto un membro o owner usando quel metodo solo se e' uno user"

Poi e' venuto fuori che anche gruppi possono essere membri e owner.
Ci do un occhio

**Comment by dbraga** [comment]
Ok allora ho capito perche' era messo li.
Praticamente c'e questo piccolo bug sulle api di google.
Normale workflow:

Aggiungo un user --> Aggiungo un gruppo --> Aggiungo uno user come membro di un gruppo

Se invece :
Aggiungi un gruppo --> Aggiungi uno user che non esiste come membro del gruppo

Lo aggiunge lo stesso.. solo che non e' mappato come user (in pratica risponde ai metodi (has_member etc) ma non essendo uno user non puo' essere navigato (informazioni di base sullo user)).

Ovviamente questo e' visibile pure sull'interfaccia web.

1) si potrebbe lasciare cosi'  e delegare all'utente di stare attento
2) si dovrebbe mettere due controlli (due find) per capire se member_id appartiene ad un User gia' presente o a un membro gia' presente (nel caso di gruppi a scatole cinesi).

Tu che ne pensi?

**Comment by davide-targa** [comment]
Io personalmente delegherei il meno possibile all'utente..
Almeno forniamo un'interfacciamento all'API che garantisca un po di consistenza negli inserimenti e nelle rimozioni.

**Comment by dbraga** [comment]
Ok quindi bisogna inserire una find e controllare se l'utente esiste prima di essere aggiunto come membro o owner di un gruppo.
Riprendo la ownership della issue
