### ISSUE TITLE
Moduli Member e Owner

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#24]
Nella classe Group c'è:

``` ruby
include Member
include Owner
```

Mentre nella classe User c'è:

``` ruby
extend Member
extend Owner
```

c'è un motivo per cui è così o è un errore?
Di certo è che bisogna uniformare, quindi è tutte e due fanno extend, o tutte e due include.

**Comment by dbraga** [comment]
Per quanto riguarda group le include mi servono allo stato attuale altrimenti non mi funzionano i metodi che chiamo da group (esempio: user_members o user_owners).
Su user c'e qualcosa di analogo che non ci permetta di uniformare ad include?

**Comment by davide-targa** [comment]
Fixed in 71d5e3d4a466f06e3bae153c2dfa20ccd8803844
