### ISSUE TITLE
formato group_id

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#26]
Mi sono accorto solo ora che il group id restituisce tutto il nome del gruppo (es: fake@damianobraga.com) e non solo "fake".  Questo è un comportamento che vogliamo?
Il problema è che non è uniforme con l'assegnamento che si fa nella new, dove si fa ad es:

``` ruby
g = RubyProvisioningApi::Group.new
g.group_id = "my_group_id"
...
```

**Comment by dbraga** [comment]
Bella domanda.
Il comportamento delle api di google non e' standard
-> le richieste funzionano sia con @domain sia con senza.

Visto che noi nella save facciamo il salvataggio senza @domain [che e' poi l'unica volta in cui google non richiede il @domain]  potremo uniformare

In ogni caso al momento attuale tutte le find/add member etc funzionano perche' appunto google risponde sempre in maniera univoca sia se richiedi con il dominio in append sia senza..

**Comment by davide-targa** [comment]
Quindi?
Se vuoi la mia opinione io farei tutto senza @domain.com, tanto quello è un parametro che si può pescare in qualunque momento dalla configurazione e che è costante per tutti gli utenti e gruppi...

**Comment by dbraga** [comment]
Ok a me va bene, appena ho un secondo c guardo

**Comment by dbraga** [comment]
148c8eb
