### ISSUE TITLE
Gestione degli environment nel file yml di configurazione

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#28]
Prevedere la gestione dei diversi ambienti nello yml

```
development
test
production
```

in caso di utilizzo della gemma in ambiente rails

**Comment by davide-targa** [comment]
Fatto: b783d8e9eebdab118dfaa93513cabcd4623f2e35
Metto in feedback

**Comment by dbraga** [comment]
Should be fine
