### ISSUE TITLE
Utilizzo della costante GROUP_ATTRIBUTES

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#29]
Classe group, nel metodo find potrebbe essere usata la costante

```
GROUP_ATTRIBUTES
```

visto che è già definita.
Inoltre sarebbe opportuno usare un iterator piuttosto che un for. Non cambia nulla ma diciamo che è più "ruby style"

**Comment by dbraga** [comment]
Closed, thanks
