### ISSUE TITLE
Utilizzo del metodo response_error?

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#31]
Nel metodo check response di Entity facciamo:

``` ruby
if (400..600).include?(response.status)
```

visto che nello stesso file abbiamo definito il metodo response_error?

``` ruby
def response_error?(response)
  (400..600).include?(response.status)
end
```

che fa esattamente la stessa cosa, usiamolo!

**Comment by dbraga** [comment]
bene
