### ISSUE TITLE
Metodo save_stub

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#33]
Il metodo save stub in `spec/ruby_provisioning_api/group_spec.rb` sembra non funzionare a dovere.
Ho commentato i relativi test per evitare fallimenti su travis.

**Comment by dbraga** [comment]
A me il test su save funziona (in locale) , mi puoi dare informazioni in piu ?

**Comment by dbraga** [comment]
Closed. the problem can not be replicated
