### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#34]
Improve gem management for test environment
Gems used for testing purposes should not be required in the "runtime" bundle
see `ruby_provisioning_api.gemspec` and `Gemfile`

**Comment by dbraga** [comment]
Ok so to test this you just need to remove all your installed gems:

**gem list | cut -d" " -f1 | xargs gem uninstall -aIx**

and then you can install all the gems with the usual command:
**bundle install**

OR you can install just the gems outside the test group with the option without

**bundle install --without=test**

**Comment by davide-targa** [comment]
When used in 'normal conditions' (i.e. in a Rails project) the gems will be installed simply with `bundle`, not with `bundle install --without=test`.
Need to investigate for other possible solutions...

**Comment by dbraga** [comment]
I just tried to bundle install on my new machine.
The test group did not install.
That's weird.

**Comment by dbraga** [comment]
Not sure what was the problem, but i resolved just re-cloning the project.
