### ISSUE TITLE
Parametro errato?

### ISSUE THREAD

**Issue by davide-targa** [digitalprog/ruby_provisioning_api#36]
Nel metodo `has_member?` di `Group` che riporto di seguito:

``` ruby
def has_member?(member_id)
  params = self.class.prepare_params_for(:has_member, { "groupId" => group_id, "memberId" => member_id })
  begin
    # Perform the request & Check if the response contains an error
    self.class.check_response(self.class.perform(params))
  rescue
    User.find(owner_id)
    false
  end    
end
```

in riga `244` c'è una find a cui passi un `owner_id`. E' quello che volevi o intendevi passare il `member_id`?

**Comment by davide-targa** [comment]
See: https://github.com/digitalprog/ruby_provisioning_api/commit/45f17120150ca8fa5c4ced42879364ac848bd2e4

**Comment by dbraga** [comment]
Uhm pensavo di aver risposto (la risposta si sara' persa da qualche parte).
Se non ricordo male questa cosa era stata fatta perche' esistevano dei membri che erano stati cancellati ma che risultavano ancora owner.

Se ti ricordi : cancellare un membro non significa automaticamente cancellarlo come owner se era entrambi. Al momento non mi sembra abbia molto senso neanche fare la find su member_id o sbaglio? tanto fai la richiesta a google due righe sopra

**Comment by davide-targa** [comment]
Ecco, mi sembrava di ricordare qualcosa del genere...
Il problema è che se inserisci come membro e owner uno con un dominio
esterno, quella find li sul rescue fallisce sempre..
Vabbè, ci riserveremo il diritto di testarlo...

Il giorno 28 novembre 2012 08:02, Damiano notifications@github.com ha
scritto:

> Uhm pensavo di aver risposto (la risposta si sara' persa da qualche parte).
> Se non ricordo male questa cosa era stata fatta perche' esistevano dei
> membri che erano stati cancellati ma che risultavano ancora owner.
> 
> Se ti ricordi : cancellare un membro non significa automaticamente
> cancellarlo come owner se era entrambi. Al momento non mi sembra abbia
> molto senso neanche fare la find su member_id o sbaglio? tanto fai la
> richiesta a google due righe sopra
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitalprog/ruby_provisioning_api/issues/36#issuecomment-10792730.

## 

Davide Targa

Ufficio Reti e Sistemi - Unità Portale
Università degli Studi di Ferrara
Tel. +39 0532 97 4155

**Comment by dbraga** [comment]
uhm interessante non ci avevo pensato!!

Damiano
