### ISSUE TITLE
Is it necessary to find a user/member/owner before delete?

### ISSUE THREAD

**Issue by dbraga** [digitalprog/ruby_provisioning_api#4]
Performance issue.
Need to investigate

**Comment by davide-targa** [comment]
No, it isn't.
Inside user I don't execute any find before the deletion, it's a class method (User.delete(user_id)) do it doesn't need an instance of user.

**Comment by dbraga** [comment]
The only reason that i could think of is when you try to delete a user/owner/group that does not exist, but in that case you'll have an exception.
So i'll go on and cut off all the finds where are not necessary
